# Uncomment the next line to define a global platform for your project
# platform :ios, '15.6'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for oi
  pod 'SnapKit', '~> 5.7.0'
  pod 'Kingfisher', '~> 6.0'
  pod 'lottie-ios'

  target 'DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoUITests' do
    # Pods for testing
  end

end
